name: CI/CD Portfolio

on:
  push:
    branches:
      - main   # staging
      - prod   # production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          IMAGE=dexlovecraft/portfolio

          if [ "${{ github.ref_name }}" = "main" ]; then
            TAG=staging
          elif [ "${{ github.ref_name }}" = "prod" ]; then
            TAG=prod
          else
            TAG=${{ github.ref_name }}
          fi

          echo "🚀 Building $IMAGE:$TAG"
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ "${{ github.ref_name }}" = "main" ]; then
              TAG=staging
            elif [ "${{ github.ref_name }}" = "prod" ]; then
              TAG=prod
            else
              TAG=${{ github.ref_name }}
            fi

            IMAGE=dexlovecraft/portfolio:$TAG
            echo "🚀 Deploying $IMAGE"
            docker pull $IMAGE
            docker compose -f /srv/portfolio/docker-compose.yml up -d portfolio-$TAG
