name: Deploy Portfolio

on:
  push:
    branches:
      - prod   # Déploiement uniquement depuis la branche prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Build du projet
      - name: Build project
        run: npm run build

      # 5. Déploiement via rsync (propre et efficace)
      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          ARGS: "-avz --delete --no-o --no-g"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: deploy
          REMOTE_PORT: ${{ secrets.VPS_PORT }}
          TARGET: "/srv/portfolio/html"
