name: Deploy CI/CD portfolio

on:
  push:
    branches:
      - prod   # Se lance uniquement sur prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project with Gulp
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/"
          target: "/srv/containers/frontend/alexXP/html"
          pre_cmd: "rm -rf /srv/containers/frontend/alexXP/html/*"
          tar_exec: true
          rm: true
          overwrite: true